import pandas as pd
import joblib
from sklearn.linear_model import LinearRegression
import mlflow

# TODO:
# 1. Load data.csv
# 2. Train a simple regression model
# 3. Log parameters, metrics to MLflow
# 4. Save model as model.pkl inside api/model.pkl

def train():
    print("Training model... TODO")

if __name__ == "__main__":
    train()
